// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixGe2T3Zh53pVm8dAYGyh5wzTWCPn5WM',
    appId: '1:858546554429:web:e1f34aefb0d9ebabaa0c54',
    messagingSenderId: '858546554429',
    projectId: 'chessmate-4e542',
    authDomain: 'chessmate-4e542.firebaseapp.com',
    storageBucket: 'chessmate-4e542.firebasestorage.app',
    measurementId: 'G-58CSYK7V2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgwkIRiswD4u2uYUGFmTgnVKviEsUi3c',
    appId: '1:858546554429:android:bec26f7951e803acaa0c54',
    messagingSenderId: '858546554429',
    projectId: 'chessmate-4e542',
    storageBucket: 'chessmate-4e542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGqkchpkEJzRZkMAOJ1QYvbVvoFLtugw',
    appId: '1:858546554429:ios:c1bd7451825b3276aa0c54',
    messagingSenderId: '858546554429',
    projectId: 'chessmate-4e542',
    storageBucket: 'chessmate-4e542.firebasestorage.app',
    iosBundleId: 'com.example.chessmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGqkchpkEJzRZkMAOJ1QYvbVvoFLtugw',
    appId: '1:858546554429:ios:c1bd7451825b3276aa0c54',
    messagingSenderId: '858546554429',
    projectId: 'chessmate-4e542',
    storageBucket: 'chessmate-4e542.firebasestorage.app',
    iosBundleId: 'com.example.chessmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCixGe2T3Zh53pVm8dAYGyh5wzTWCPn5WM',
    appId: '1:858546554429:web:f3c335c1b0745b58aa0c54',
    messagingSenderId: '858546554429',
    projectId: 'chessmate-4e542',
    authDomain: 'chessmate-4e542.firebaseapp.com',
    storageBucket: 'chessmate-4e542.firebasestorage.app',
    measurementId: 'G-T36C9S68FD',
  );
}
